version: '3'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    env_file: .env
    healthcheck: 
       test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
    networks:
      - back
    expose:
      - 5432

  prisma-studio: 
     image: timothyjmiller/prisma-studio:latest 
     container_name: prisma-studio 
     ports: 
       - "127.0.0.1:5555:5555" 
     restart: always 
     env_file: 
       - .env 
     depends_on: 
       postgres: 
         condition: service_healthy 
     entrypoint: ['node_modules/.bin/prisma', 'studio'] 
     volumes: 
       - ./backend/prisma/schema.prisma:/schema.prisma 
     networks: 
       - back

  backend:
    container_name: backend
    env_file: .env
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/back
      - /back/node_modules
    networks:
      - back
    ports:
      - 3000:3000
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/front/
      - /front/node_modules
    ports:
      - 8000:8000

networks:
  back:
