version: '3'
services:
  backend:
    container_name: backend
    env_file: .env
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/back
    ports:
      - 3000:3000
  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/front
    ports:
      - 8000:8000